export default function TermsPage() {
  return (
    <div className="p-8 max-w-3xl mx-auto prose prose-invert prose-sm">
      <h1 className="text-2xl font-bold mb-6">Terms of Service</h1>
      <p className="text-text-secondary">Last updated: March 19, 2026</p>

      <h2 className="text-lg font-semibold mt-6">1. Service Description</h2>
      <p className="text-text-secondary">Vaxario is an AI-powered tool that generates and deploys SaaS applications based on user-provided ideas. The service uses Claude AI for code generation and various third-party APIs for deployment.</p>

      <h2 className="text-lg font-semibold mt-6">2. BYOK Model</h2>
      <p className="text-text-secondary">Vaxario operates on a Bring Your Own Keys (BYOK) model. You provide your own API keys for Anthropic, GitHub, Vercel, and Supabase. We do not share your API keys with third parties. API usage costs from these providers are your responsibility.</p>

      <h2 className="text-lg font-semibold mt-6">3. Credits & Billing</h2>
      <p className="text-text-secondary">Credits are consumed when pipeline steps are executed. Unused credits do not roll over between billing periods. Refunds are handled on a case-by-case basis.</p>

      <h2 className="text-lg font-semibold mt-6">4. Generated Code</h2>
      <p className="text-text-secondary">All code generated by Vaxario belongs to you. You have full ownership and can modify, distribute, or sell applications built with this service.</p>

      <h2 className="text-lg font-semibold mt-6">5. Limitation of Liability</h2>
      <p className="text-text-secondary">Vaxario is provided &ldquo;as is&rdquo; without warranties. We are not responsible for the quality, security, or functionality of generated applications. You are responsible for reviewing and testing generated code before production use.</p>

      <h2 className="text-lg font-semibold mt-6">6. Contact</h2>
      <p className="text-text-secondary">For questions about these terms, contact us at support@saasfactory.dev</p>
    </div>
  )
}
